### ISSUE TITLE
Adding fields to template

### ISSUE THREAD

**Issue by malcolmevans** [itteco/meteor-oembed#1]
Hi there,

I'm trying to create a meteor form with 3 fields. Title, description and URL. Once the form is submitted the title and description would appear above the embedded URL. I have your base code working to type in a video url and have it appear embedded, but am struggling to add the title & description fields to the template.

Can you help me? I'm a coding newbie so please forgive if its a basic question.

Thanks!

**Comment by nleush** [comment]
If your data record has format:

```
{
  title: 'Some video',
  description: 'Video description',
  url: 'http://www.youtube.com/?v=sf73k'
}
```

Then like in example project (https://github.com/nleush/meteor-iframely-demo/blob/master/client/urls.html) your template will look like:

```
{{#each items}}
  <p>{{title}}</p>
  <p>{{description}}</p>
  <p>
    {{>oembed}}
  </p>
{{/each}}
```

**Comment by malcolmevans** [comment]
Thank you for your response Nazar!

I think my difficulty is in getting the embed event to add multiple data fields to the data record. Any time i introduce new variables, the core embed function stops working.

I've created a demo repo here: https://github.com/malcolmevans/iframely-addingfields - and the last commit shows the changes I've been trying to make. Any chance you can give a quick peek to see what I might be doing wrong?

Thank you so much!!

**Comment by nleush** [comment]
Add row:

```
Tasks = new Mongo.Collection("tasks");
```

to `server/common.js`

Its workaround of insecure package to work with collection on server side.

**Comment by malcolmevans** [comment]
Wow, so simple, thank you!!!
